src/Entity/ReturnSettings.php
<?php

namespace App\Entity;

use App\Repository\ReturnSettingsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\NotBlankValidator;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReturnSettingsRepository")
 * @ORM\Table(name="return_settings")
 */
class ReturnSettings
{
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $image_logo;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $image_background;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    private $return_period;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImageLogo(): ?string
    {
        return $this->image_logo;
    }

    public function setImageLogo(string $image_logo): self
    {
        $this->image_logo = $image_logo;

        return $this;
    }

    public function getImageBackground(): ?string
    {
        return $this->image_background;
    }

    public function setImageBackground(string $image_background): self
    {
        $this->image_background = $image_background;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getReturnPeriod(): ?int
    {
        return $this->return_period;
    }

    public function setReturnPeriod(int $return_period): self
    {
        $this->return_period = $return_period;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }
    
}

src/Entity/Returns/ReturnSettings.php
<?php

namespace App\Entity\Returns;

use App\Entity\Common\Country;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Returns\ReturnSettingsRepository")
 * @ORM\Table(name="return_settings")
 */
class ReturnSettings
{
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

     /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $company_name;

     /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $client_name;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $phone;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $email;
    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $title;

     /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $image_logo;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $image_background;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    private $return_period;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $street;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $house_nummber;

    /**
     * @var Country
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Common\Country", inversedBy="settings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $country;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city_name;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
    */
    private $post_code;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImageLogo(): ?string
    {
        return $this->image_logo;
    }

    public function setImageLogo(string $image_logo): self
    {
        $this->image_logo = $image_logo;

        return $this;
    }

    public function getImageBackground(): ?string
    {
        return $this->image_background;
    }

    public function setImageBackground(string $image_background): self
    {
        $this->image_background = $image_background;

        return $this;
    }

   
    public function getCompanyName(): ?string
    {
        return $this->company_name;
    }

    public function setCompanyName(string $company_name): self
    {
        $this->company_name = $company_name;

        return $this;
    }

    public function getClientName(): ?string
    {
        return $this->client_name;
    }

    public function setClientName(string $client_name): self
    {
        $this->client_name = $client_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }


    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getReturnPeriod(): ?int
    {
        return $this->return_period;
    }

    public function setReturnPeriod(int $return_period): self
    {
        $this->return_period = $return_period;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(?string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getHouseNumber(): ?string
    {
        return $this->house_nummber;
    }
    
    public function setHouseNumber(?string $house_nummber): void
    {
        $this->house_nummber = $house_nummber;
    }

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(?Country $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getCityName(): ?string
    {
        return $this->city_name;
    }

    public function setCityName(?string $city_name): self
    {
        $this->city_name = $city_name;

        return $this;
    }

    public function getPostCode(): ?string
    {
        return $this->post_code;
    }

    public function setPostCode(?string $post_code): self
    {
        $this->post_code = $post_code;

        return $this;
    }
    
}

src/Controller/ReturnSettingsController.php
<?php

namespace App\Controller;

use App\Entity\Common\Country;
use App\Entity\Common\NlCity;
use App\Entity\Returns\Status;
use App\Form\ReturnSettingsType;
use App\Entity\Returns\PayCategory;
use App\Entity\Returns\ReturnSettings;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\Returns\ReturnSettingsRepository;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

/**
    * @Route("/settings")
*/
class ReturnSettingsController extends AbstractController
{
    private $data = [];
    private $payments = [];

    public function __construct(ManagerRegistry $doctrine)
    {

        //everybody will extends status for vertical sidebar -- for email template customization
        $this->data = $doctrine->getRepository(Status::class)->findAll();
        $this->payments = $doctrine->getRepository(PayCategory::class)->findAll();

  
    }

    /**
     * @Route("/", name="app_return_settings_index", methods={"GET"})
     */
    public function index(ReturnSettingsRepository $returnSettingsRepository): Response
    {
        return $this->render('return_settings/index.html.twig', [
            'return_settings' => $returnSettingsRepository->findAll(),
        ]);
    }
    /**
     * @Route("/create", name="app_return_settings_new")
     */
    public function new(ManagerRegistry $doctrine, Request $request, ReturnSettingsRepository $returnSettingsRepository, SluggerInterface $slugger): Response
    {
        $settings = $doctrine->getRepository(ReturnSettings::class)->findAll();
        
        if($settings)
        {
           return  $this->redirectToRoute('app_return_settings_edit');
        }
        $countries = $doctrine->getRepository(Country::class)->findAll();
        $returnSetting = new ReturnSettings();
        $form = $this->createForm(ReturnSettingsType::class, $returnSetting);
        $form->handleRequest($request);

        $logoimage = $form->get('image_logo')->getData();
        $backgroundimage = $form->get('image_background')->getData();
        // $country = $form->get('countries')->getData();
        $street = $form->get('street')->getData();
        $postcode = $form->get('postcode')->getData();
      
        if ($form->isSubmitted()) {

            $requestis = $request->request->all();
            $email = $requestis['return_settings']['email'];
            $phone = $requestis['return_settings']['phone'];
            $countryId = $requestis['return_settings']['countries'];
            
            $currentroute = $request->headers->get('referer');

            if (!filter_var($email, FILTER_VALIDATE_EMAIL)) 
            {
                $this->addFlash('er-email', 'Email is not in good format');
                return $this->redirect($currentroute);       
            } 

            if(!preg_match("/^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$/", $phone))
            {
                $this->addFlash('er-phone', 'Phone must be in format: +xxxxxxxxxxxx or'.'   xxxxxxxxxx or'.
                '  +xxxxxxxxxxx or '.'  xxx-xxx-xxxx');
                return $this->redirect($currentroute);     
            }
            
            if($countryId == 0)
            {
               
                $this->addFlash('er-country', 'Country is required field');
                return $this->redirect($currentroute);       
            }
           

            if($logoimage)
            {
                $originalFilename = pathinfo($logoimage->getClientOriginalName(), PATHINFO_FILENAME);
                
                $safeFilename = $slugger->slug($originalFilename);
                $newLogo = $safeFilename.'-'.uniqid().'.'.$logoimage->guessExtension();

                
                try {
                    $logoimage->move(
                        $this->getParameter('return_settings_images'),
                        $newLogo
                    );
                } catch (FileException $e) {

                    $e = $this->renderView('errors/500.html.twig', []);
                    return new Response($e, 500);
                }
            }
            if($backgroundimage)
            {
                $originalFilename = pathinfo($backgroundimage->getClientOriginalName(), PATHINFO_FILENAME);
                
                $safeFilename = $slugger->slug($originalFilename);
                $newBackground = $safeFilename.'-'.uniqid().'.'.$backgroundimage->guessExtension();

                
                try {
                    $backgroundimage->move(
                        $this->getParameter('return_settings_images'),
                        $newBackground
                    );
                } catch (FileException $e) {

                    $e = $this->renderView('errors/500.html.twig', []);
                    return new Response($e, 500);
                }
            }
            
          

            $cityfromrequest = $requestis['return_settings']['city'];
            $housenum = $requestis['return_settings']['house_nummber'];
        
            $country = $doctrine->getRepository(Country::class)->findOneBy(['id'=>$countryId]);

            
            if(!$country)
            {
                $this->addFlash('er-country', 'Choose country from current list');
                return $this->redirect($currentroute);       
            }
            
            // $city = $doctrine->getRepository(NlCity::class)->findOneBy(['id'=>$cityfromrequest]);
            // return dd($country);
           
            $returnSetting->setCountry($country);
            $returnSetting->setCityName($cityfromrequest);
            $returnSetting->setHouseNumber($housenum);
            $returnSetting->setImageLogo($newLogo);
            $returnSetting->setImageBackground($newBackground);
            // $returnSetting->setCountry($country);
            $returnSetting->setStreet($street);
            $returnSetting->setPostCode($postcode);
            $returnSettingsRepository->add($returnSetting);

            $this->addFlash('success', 'You updated settings successfully');
            return $this->redirectToRoute('app_return_settings_edit', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('return_settings/new.html.twig', [
            'return_setting' => $returnSetting,
            'countries' => $countries,
            'form' => $form,
            'status' => $this->data,
            'payments' => $this->payments
        ]);
    }

   
    /**
     * @Route("/edit", name="app_return_settings_edit", methods={"GET", "POST"})
     */
    public function edit(ManagerRegistry $doctrine, Request $request,  ReturnSettingsRepository $returnSettingsRepository, SluggerInterface $slugger): Response
    {
       
        
        $returnSetting = $doctrine->getRepository(ReturnSettings::class)->findOneBy([]);
        $currentCountryName = $returnSetting->getCountry()->getName();
        $currentCountryId = $returnSetting->getCountry()->getId();
        $countries = $doctrine->getRepository(Country::class)->findAll();

        
        // $cities = $doctrine->getRepository(NlCity::class)->findAll();
       
        // if($returnSetting->getCountry()->getName() == "Netherlands")
        // {
        //     $cityName = $returnSetting->getCityName();
        //     $findCity = $doctrine->getRepository(NlCity::class)->findOneBy(['name'=>$cityName]);
        //     $nlId = $findCity->getId();
        //     $nlName = $findCity->getName();

        // }
        // else
        // {
        //     $nlId = "";
        // }

        if(!$returnSetting)
        {
            return $this->redirectToRoute('app_return_settings_new');
        }
        // $logo = $returnSetting->getImageLogo();
        // $background = $returnSetting->getImageBackground();

        $lastimagelogo = $returnSetting->getImageLogo();
        $lastimagebackground = $returnSetting->getImageBackground();
        
        $form = $this->createForm(ReturnSettingsType::class, $returnSetting);
        $form->handleRequest($request);
        
        if ($form->isSubmitted()) {
           
            
            $images = $request->files->all();
           
            $logoimage = $images['return_settings']['image_logo'];
            $backgroundimage =  $images['return_settings']['image_background'];
           
            if($logoimage != null)
            {
               
                $originalFilename = pathinfo($logoimage->getClientOriginalName(), PATHINFO_FILENAME);
                
                $safeFilename = $slugger->slug($originalFilename);
                $newLogo = $safeFilename.'-'.uniqid().'.'.$logoimage->guessExtension();
                
                
                try {

                    
                    $fs = new Filesystem();
                   
                    $fs->remove($this->getParameter('return_settings_images').'/'.$lastimagelogo);
                
                    $logoimage->move(
                        $this->getParameter('return_settings_images'),
                        $newLogo
                    );
                   
                    $returnSetting->setImageLogo($newLogo);

                } catch (FileException $e) {

                    $e = $this->renderView('errors/500.html.twig', []);
                    return new Response($e, 500);
                }

                
            }
            else
            {
                $returnSetting->setImageLogo($returnSetting->getImageLogo());
            }
              
            if($backgroundimage != null)
            {
                $originalFilename = pathinfo($backgroundimage->getClientOriginalName(), PATHINFO_FILENAME);

templates/return_settings/edit.html.twig
{% extends 'main-metronic.html.twig' %}

{% block title %}Edit ReturnSettings{% endblock %}
{% block stylesheet %}
   <link href="{{asset('/assets/css/return.css')}}" rel="stylesheet" type="text/css">
{% endblock %}
{% block content %}
<div class="container-xxl mt-17 pt-5">

{{include('/components/alert-message.html.twig')}}

<div class="row">
    <div class="col-lg-3 col-xl-2">
        {{include('/components/vertical-sidebar.html.twig')}}
    </div>
    <div class="col-lg-7">
    <div class="kt-portlet__head">
        <div class="kt-portlet__head-label">
            <h3 class="kt-portlet__head-title">General settings</h3>
        </div>
    </div>
    <div class="card no-radius">
    <div class="card-body">

        

        {{ form_start(form, { 'attr': {'enctype': 'multipart/form-data'} }) }}
         <div class="row mb-6 mt-2">
               <div class="col-lg-4 text-right">
                    {{ form_label(form.company_name) }}
                </div>
                <div class="col-lg-8">
                    {{ form_widget(form.company_name) }}
                    <small>{{ form_help(form.company_name) }}</small>
                    <div class="form-error col-lg-7 text-danger">
                        {{ form_errors(form.company_name) }}
                    </div>
                </div>
            </div>
            <div class="row mb-6 mt-2">
               <div class="col-lg-4 text-right">
                    {{ form_label(form.client_name) }}
                </div>
                <div class="col-lg-8">
                    {{ form_widget(form.client_name) }}
                    <small>{{ form_help(form.client_name) }}</small>
                    <div class="form-error col-lg-7 text-danger">
                        {{ form_errors(form.client_name) }}
                    </div>
                </div>
            </div>
            <div class="row mb-6 mt-2">
               <div class="col-lg-4 text-right">
                    {{ form_label(form.phone) }}
                </div>
                <div class="col-lg-8">
                    {{ form_widget(form.phone) }}
                    <small>{{ form_help(form.phone) }}</small>
                    <div class="form-error col-lg-7 text-danger">
                        {{ form_errors(form.phone) }}
                    </div>
                    {% for message in app.flashes('er-phone') %}
                         <div class="form-error col-lg-7 text-danger">
                            {{ message }}
                        </div>  
                    {% endfor %} 
                </div>
            </div>
            <div class="row mb-6 mt-2">
               <div class="col-lg-4 text-right">
                    {{ form_label(form.email) }}
                </div>
                <div class="col-lg-8">
                    {{ form_widget(form.email) }}
                    <small>{{ form_help(form.email) }}</small>
                    <div class="form-error col-lg-7 text-danger">
                        {{ form_errors(form.email) }}
                    </div>
                     {% for message in app.flashes('er-email') %}
                         <div class="form-error col-lg-7 text-danger">
                            {{ message }}
                        </div>  
                    {% endfor %} 
                </div>
            </div>
            <div class="row mb-6 mt-10">
                <div class="col-lg-4 text-right">
                {{ form_label(form.image_logo) }} 
                </div>
                <div class="col-lg-8">
                    <div class="image-input image-input-outline image-input-changed" data-kt-image-input="true" style="background-image: url('{{asset('/return_settings_images/')}}{{return_setting.getImageLogo()}}');">
                        <div class="image-input-wrapper w-125px h-125px" style="background-size: contain;
    background-position: center; background-image: url('{{asset('/return_settings_images/')}}{{return_setting.getImageLogo()}}"></div>
                        <label class="btn btn-icon btn-circle btn-active-color-primary w-25px h-25px bg-body shadow" data-kt-image-input-action="change" data-bs-toggle="tooltip" title="" data-bs-original-title="Insert logo">
                           <i class="fas fa-pen text-muted"></i>
                          {{ form_widget(form.image_logo) }}
                        </label>
                    </div>
                    <small>{{ form_help(form.image_logo) }}</small>
                    <div class="form-error col-lg-7 text-danger">
                    {{ form_errors(form.image_logo) }}
                </div>
                </div>
            </div>
            <div class="row mb-6 mt-2">
               <div class="col-lg-4 text-right mt-5">
                {{ form_label(form.image_background) }} 
                </div>
                <div class="col-lg-8">
                    <div class="image-input image-input-outline image-input-changed" data-kt-image-input="true" style="background-image: url('{{asset('/return_settings_images/')}}{{return_setting.getImageBackground()}}')">
                        <div class="image-input-wrapper w-125px h-125px" style="background-image: url('{{asset('/return_settings_images/')}}{{return_setting.getImageBackground()}}')"></div>
                        <label class="btn btn-icon btn-circle btn-active-color-primary w-25px h-25px bg-body shadow" data-kt-image-input-action="change" data-bs-toggle="tooltip" title="" data-bs-original-title="Insert image background">
                           <i class="fas fa-pen text-muted"></i>
                            {{ form_widget(form.image_background, {'value': return_setting.getImageBackground() }) }}
                        </label>
                    </div>
                    <small>{{ form_help(form.image_background) }}</small>
                    <div class="form-error col-lg-7 text-danger">
                        {{ form_errors(form.image_background) }}
                    </div>
                </div>
            </div>
           
             <div class="row mb-6 mt-2">
               <div class="col-lg-4 text-right">
                    {{ form_label(form.title) }}
                </div>
                <div class="col-lg-8">
                    {{ form_widget(form.title) }}
                    <small>{{ form_help(form.title) }}</small>
                    <div class="form-error col-lg-7 text-danger">
                        {{ form_errors(form.title) }}
                    </div>
                </div>
            </div>
            <div class="row mb-6 mt-2">
               <div class="col-lg-4 text-right">
                    {{ form_label(form.status) }}
                </div>
                <div class="col-lg-8">
                    {{ form_widget(form.status) }}
                    <small>{{ form_help(form.status) }}</small>
                    <div class="form-error col-lg-7 text-danger">
                        {{ form_errors(form.status) }}
                    </div>
                </div>
            </div>
             <div class="row mb-6 mt-2">
               <div class="col-lg-4 text-right">
                    {{ form_label(form.return_period) }}
                </div>
                <div class="col-lg-8">
                    {{ form_widget(form.return_period) }}
                    <small>{{ form_help(form.return_period) }}</small>
                    <div class="form-error col-lg-7 text-danger">
                        {{ form_errors(form.return_period) }}
                    </div>
                </div>
            </div>
              <div class="row mb-6 mt-2">
               <div class="col-lg-4 text-right">
                   <label class="required"> Countries</label>
                </div>
                <div class="col-lg-8">
                    <select name="return_settings[countries]" class="form-control">
                        <option value="{{countryid}}">{{countryname}}</option>
                        {% for country in countries %}
                        <option value="{{country.getId()}}">{{country.getName()}}</option>
                        {% endfor %}
                    </select>
                     {% for message in app.flashes('er-country') %}
                         <div class="form-error col-lg-7 text-danger">
                            {{ message }}
                        </div>  
                    {% endfor %} 
                </div>
            </div>
            <div class="row mb-6 mt-2">
               <div class="col-lg-4 text-right">
                    {{ form_label(form.city) }}
                </div>
                <div class="col-lg-8">
                    {{ form_widget(form.city) }}
                    <small>{{ form_help(form.city) }}</small>
                    <div class="form-error col-lg-7 text-danger">
                        {{ form_errors(form.city) }}
                    </div>
                </div>
            </div>
            <div class="row mb-6 mt-2">
               <div class="col-lg-4 text-right">
                    {{ form_label(form.street) }}
                </div>
                <div class="col-lg-8">
                    {{ form_widget(form.street) }}
                    <small>{{ form_help(form.street) }}</small>
                    <div class="form-error col-lg-7 text-danger">
                        {{ form_errors(form.street) }}
                    </div>
                </div>
            </div>
              <div class="row mb-6 mt-2">
               <div class="col-lg-4 text-right">
                    {{ form_label(form.house_nummber) }}
                </div>
                <div class="col-lg-8">
                    {{ form_widget(form.house_nummber) }}
                    <small>{{ form_help(form.house_nummber) }}</small>
                    <div class="form-error col-lg-7 text-danger">
                        {{ form_errors(form.house_nummber) }}
                    </div>
                </div>
            </div>
             <div class="row mb-6 mt-2">
               <div class="col-lg-4 text-right">
                    {{ form_label(form.postcode) }}
                </div>
                <div class="col-lg-8">
                    {{ form_widget(form.postcode) }}
                    <small>{{ form_help(form.postcode) }}</small>
                    <div class="form-error col-lg-7 text-danger">
                        {{ form_errors(form.postcode) }}
                    </div>
                </div>
            </div
             <div class="row mb-6 mt-2">
             <div class="kt-portlet__foot">
            <div class="kt-form__actions">
                <div class="row">
                    <div class="col-lg-4 col-xl-4">
                    </div>
                    <div class="col-lg-8 col-xl-8 p-l0">
                    <button class="btn btn-success mt-3 btn-sm">{{ button_label|default('Save') }}</button>
                    </div>
                </div>
            </div>
        </div>
                
                </div>
            </div>
         {{ form_end(form) }}
        </div>
     </div>
    </div>
</div>
</div>


{% endblock %}

templates/return_settings/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ReturnSettings index{% endblock %}

{% block body %}
    <h1>ReturnSettings index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Image_logo</th>
                <th>Image_background</th>
                <th>Title</th>
                <th>Return_period</th>
                <th>Status</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for return_setting in return_settings %}
            <tr>
                <td>{{ return_setting.id }}</td>
                <td>{{ return_setting.imageLogo }}</td>
                <td>{{ return_setting.imageBackground }}</td>
                <td>{{ return_setting.title }}</td>
                <td>{{ return_setting.returnPeriod }}</td>
                <td>{{ return_setting.status }}</td>
                <td>
                    <a href="{{ path('app_return_settings_show', {'id': return_setting.id}) }}">show</a>
                    <a href="{{ path('app_return_settings_edit', {'id': return_setting.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_return_settings_new') }}">Create new</a>
{% endblock %}